# name of the CI workflow pipeline
name: SWT CI Workflow

# describe the trigger
on:
  push:
    branches: "**"
  pull_request:
    branches: [main]

# jobs definitions after trigger occurs
jobs:
  # first job shall be testing
  test:
    runs-on: ubuntu-latest
    steps:
      # 1st step: checkout code from git
      - uses: actions/checkout@v4
      # 2nd step: setup Java environment
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          # enabling maven caching dependencies
          cache: "maven"
          cache-dependency-path: "backend/pom.xml"
      # 3rd step: run tests using maven
      - name: Run Tests
        working-directory: backend
        run: |
          ./mvnw test
